### ISSUE TITLE
Cannot reset the password in the web console

### ISSUE THREAD

**Issue by QAInsights** [awslabs/distributed-load-testing-on-aws#1]
When I try to reset the password in the Console URL, it is displaying below error message.
`User password cannot be reset in the current state`, 

**This error occurs, if the user did not confirm their account for the first time, and trying to reset the password.**

**Steps to reproduce**

1. Create a stack using the [template](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?&templateURL=https:%2F%2Fs3.amazonaws.com%2Fsolutions-reference%2Fdistributed-load-testing-on-aws%2Flatest%2Fdistributed-load-testing-on-aws.template)
2. After successful creation, launch the console URL from the Outputs tab in the Cloudformation service
3. Click on Reset password.
4. Enter username
5. Click on SEND CODE

**Actual Behavior**

It is displaying `User password cannot be reset in the current state.`

**Expected Behavior**

Display message can be more meaningful. E.g. `Account not confirmed, please check your administrator email`

**Comment by tomnight** [comment]
Hi there,
Did you receive an email with the temporary password? the workflow with cognito is:

- user registered (during deployment)
- email confirmation sent with temporary password
- login with temporary password and then set actual password. 

until this is done the rest password will note work.

**Comment by QAInsights** [comment]
Yes @tomnight I did received the credentials in the email. When I tested the forgot password link without confirming my account, it displayed `User password cannot be reset in the current state.`. 

I believe `Account not confirmed, please check your administrator email` message will have more clarity.

**Comment by tomnight** [comment]
resolving inactive issue, please reach out if you have any other questions
