### ISSUE TITLE
Fargate Tasks fail to finish

### ISSUE THREAD

**Issue by branst** [awslabs/distributed-load-testing-on-aws#11]
Context:

Task Count: 40
Tps per Task: 100

Time to peak: 5m
TIme to hold: 10m

Of the 40 taks, around 5-10 of them usually to finish and i cannot see the result since the task is still on the 'Running' State. My options are to stop the task or to evict the taks from ECS and review the results manually on Dynamo.

Even waiting 1-5 hours after the defined time to reach peak and hold, doens't seem to have any effect. There is still some taks still hanged.

**Comment by branst** [comment]
<img width="914" alt="Screen Shot 2020-05-08 at 10 11 07" src="https://user-images.githubusercontent.com/50686099/81413943-44ed5780-9114-11ea-9d67-50ad56f992bf.png">

Details of the task. After 1+ hour runnings still one taks is on runnings state.

**Comment by tomnight** [comment]
Each container writes the test results to S3 as an xml file. This put object event triggers the results-parser lambda function which will parse the xml file and transfer the results to DynamoDB.  The final step is to check the number of results in DynamoDB against the number of task that ran. If all the results have been parsed the Lambda function then combines all of the results and set the status in DynamoDB to complete.

I suspect this last step failed. Checking the CloudWatch logs for the the lambda function may shed some light on this.  Also is this the only time or has this happened multiple times?

**Comment by mmarseglia** [comment]
I'm having the same problem.  The log files are in the bucket and haven't been processed by the lambda.  Is it possible the lambda isn't receiving the put object event trigger?

**Comment by beomseoklee** [comment]
We've released v1.1.0, and I believe v1.1.0 fixes this issue. Please see the details in [CHANGELOG](https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/CHANGELOG.md).
