### ISSUE TITLE
Uploading CSV Data Set Config for JMeter

### ISSUE THREAD

**Issue by QAInsights** [awslabs/distributed-load-testing-on-aws#18]
How can we upload the CSV Data Set Config file which will be used in the JMeter script? Right now, I do not see any option to upload in the web console. Please clarify.

**Comment by beomseoklee** [comment]
@QAInsights Currently, we only support to upload JMeter script. Can you describe your use case in detail?

**Comment by QAInsights** [comment]
@beomseoklee Typically we store all the test data in CSV file. Using [CSV Data Set Config](https://jmeter.apache.org/usermanual/component_reference.html#CSV_Data_Set_Config) element in JMeter, we call them using the variable name. 

Testing with different set of data is crucial for performance testing. This will help us to simulate real world scenario.

**Comment by beomseoklee** [comment]
@QAInsights We've released v1.2.0, and the new version supports to include CSV input files.

Please see more information [here](https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/considerations.html).)

**Comment by QAInsights** [comment]
@beomseoklee I am on it :)

**Comment by QAInsights** [comment]
@beomseoklee I have tested it. It is working fine. You can check my video here [https://www.youtube.com/watch?v=RyoRQNXxyDY](https://www.youtube.com/watch?v=RyoRQNXxyDY). 
It is taking too much time to start the test. Is that expected?

**Comment by beomseoklee** [comment]
@QAInsights Thanks for sharing your testing result and feedback. The way it works is that once you start the test, it provisions AWS Fargate tasks and starts the AWS Fargate tasks. It takes a time to provision the AWS Fargate tasks, so it takes time to start the test actually.

**Comment by QAInsights** [comment]
Thanks for the clarification @beomseoklee
