### ISSUE TITLE
create EC

### ISSUE THREAD

**Issue by gyj0825** [awslabs/distributed-load-testing-on-aws#2]
environment：
Region：us-west-2

When I normally create a stack, I start a test task and find that the lambda function load-test-TaskRunner cannot start ECS tasks. The error log is displayed as follows:
```
2019-11-19T15:56:23.543Z	28972b44-f39d-502e-bfad-7d0ae15297ac	INFO	{ InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'Unable to assume the service linked role. Please verify that the ECS service linked role exists.',
  code: 'InvalidParameterException',
  time: 2019-11-19T15:56:23.499Z,
  requestId: '7a6d7064-768a-425f-bfae-698c0515e607',
  statusCode: 400,
  retryable: false,
  retryDelay: 71.86203577055117 }
```
I checked that the Execution role of the lambda is there.
What is wrong with my environment?

**Comment by tomnight** [comment]
the lambda role points to a managed policy that may not have been setup in you account/region.  In the error message you can see::
Unable to assume the service linked role. Please verify that the ECS service linked role exists.',

Template Line 395: "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

I would verify this exists and if not re create it, details on the role can be found here:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html

the policy should look something like:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ECSTaskManagement",
            "Effect": "Allow",
            "Action": [
                "ec2:AttachNetworkInterface",
                "ec2:CreateNetworkInterface",
                "ec2:CreateNetworkInterfacePermission",
                "ec2:DeleteNetworkInterface",
                "ec2:DeleteNetworkInterfacePermission",
                "ec2:Describe*",
                "ec2:DetachNetworkInterface",
                "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                "elasticloadbalancing:DeregisterTargets",
                "elasticloadbalancing:Describe*",
                "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                "elasticloadbalancing:RegisterTargets",
                "route53:ChangeResourceRecordSets",
                "route53:CreateHealthCheck",
                "route53:DeleteHealthCheck",
                "route53:Get*",
                "route53:List*",
                "route53:UpdateHealthCheck",
                "servicediscovery:DeregisterInstance",
                "servicediscovery:Get*",
                "servicediscovery:List*",
                "servicediscovery:RegisterInstance",
                "servicediscovery:UpdateInstanceCustomHealthStatus"
            ],
            "Resource": "*"
        },
        {
            "Sid": "ECSTagging",
            "Effect": "Allow",
            "Action": [
                "ec2:CreateTags"
            ],
            "Resource": "arn:aws:ec2:*:*:network-interface/*"
        },
        {
            "Sid": "CWLogGroupManagement",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:DescribeLogGroups",
                "logs:PutRetentionPolicy"
            ],
            "Resource": "arn:aws:logs:*:*:log-group:/aws/ecs/*"
        },
        {
            "Sid": "CWLogStreamManagement",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:log-group:/aws/ecs/*:log-stream:*"
        }
    ]
}

**Comment by tomnight** [comment]
Closing old issue.
