### ISSUE TITLE
support image upload in the future?

### ISSUE THREAD

**Issue by jhaoheng** [awslabs/distributed-load-testing-on-aws#22]
Does it support the upload file/image/binary in the future?
Or there has some approach that could upload a file for the test?

Thanks

**Comment by beomseoklee** [comment]
@jhaoheng thanks for contacting us. May I know the specific use cases you are looking for?

**Comment by jhaoheng** [comment]
Hi, thanks for your reply.
I try to test my upload image API for my solution. And hope to get my serverless limitation.

**Comment by beomseoklee** [comment]
@jhaoheng oh, I see what you mean. Currently, we don't support that, but I think by the time we support to upload the input files, your use case would be supported. I'll update you once we release the new version.

**Comment by beomseoklee** [comment]
@jhaoheng We've released v1.2.0, and the new version supports input files with the script as well. You can include your images in your JMeter script and zip everything.

Please see more information [here](https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/considerations.html).

**Comment by jhaoheng** [comment]
Amazing!! It's really useful, thanks a lot. I will try it later.
