### ISSUE TITLE
5 MB file limit seems arbitrary and small

### ISSUE THREAD

**Issue by ryanneill-sterling** [awslabs/distributed-load-testing-on-aws#23]
Is there any reason to keep this so low? Can we bump it to 50 / 100 MB?

https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/source/console/src/Components/Create/Create.js#L25

https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/source/console/src/Components/Create/Create.js#L216

**Comment by ryanneill-sterling** [comment]
https://github.com/awslabs/distributed-load-testing-on-aws/pull/24

**Comment by beomseoklee** [comment]
@ryanneill-sterling Thanks for your feedback. Do you have any use case?

**Comment by ryanneill-sterling** [comment]
@beomseoklee Yes. One of my teammates has a 20 MB jmx file that embeds a bunch of csv data to do handle a bunch of specific user requests in particular order. Do you need more details than that?

I can't provide the specific JMX file given it contains proprietary information.

Is there a technical reason this has been set to 5 MB file size?

**Comment by beomseoklee** [comment]
Thanks for your information @ryanneill-sterling 
That's enough for us, and we will validate if it's OK to increase the maximum file size. Meanwhile, if you want, you can change the source code, and redeploy to your environment. In addition, we are preparing csv input files upload as well.

**Comment by ryanneill-sterling** [comment]
One other change is needed in the CFT, ScenariosBucket -> CorsConfiguration -> CorsRules needs to have ExposedHeaders added with at least "ETag" (I just added the other recommended headers as well from Amplify Storage docs).

**Comment by beomseoklee** [comment]
@ryanneill-sterling We've released v1.2.0, and we've updated to support 50MB file.
https://github.com/awslabs/distributed-load-testing-on-aws/blob/339482f2ee9a1501b4db49da33cd656c6f3f6110/source/console/src/Components/Create/Create.js#L24-L25

**Comment by ryanneill-sterling** [comment]
@beomseoklee Excellent, thanks! Did you need the ExposedHeaders bit as well or is this small enough to not trigger multi-part?

**Comment by ryanneill-sterling** [comment]
Looks like yes. Thanks again!
