### ISSUE TITLE
Order Dashboard jobs listing by Last Run Descending

### ISSUE THREAD

**Issue by ryanneill-sterling** [awslabs/distributed-load-testing-on-aws#25]
Current ordering by name of job is a bit unpredictable if multiple teams are doing various custom runs. Ordering by last run descending means most recent runs will show up at the top and make this tool easier to use.

Alternatively, adding a toggle on each column would also be a suitable solution but I think what I've suggested above is a better default if you do this then the current by name.

If it helps I can submit a pull request for this I expect. Haven't dug into the particular code details yet.

**Comment by beomseoklee** [comment]
@ryanneill-sterling Thanks for your feedback, and we will include this one to the next release.

**Comment by ryanneill-sterling** [comment]
It's probably immediately obvious how/where this can be done but just in case it isn't, I updated line 59 of source/console/src/Components/Dashboard/Dashboard.js with an extra chained sort to achieve this for the meantime:

`Items.sort((b, a) => a.startTime < b.startTime ? -1 : (a.startTime > b.startTime ? 1 : 0)).map(item => (`

Prior:

`Items.map(item => (`

**Comment by beomseoklee** [comment]
@ryanneill-sterling We've released v1.2.0, and we've changed this.
https://github.com/awslabs/distributed-load-testing-on-aws/blob/339482f2ee9a1501b4db49da33cd656c6f3f6110/source/console/src/Components/Dashboard/Dashboard.js#L21-L42

**Comment by ryanneill-sterling** [comment]
Thanks!
