### ISSUE TITLE
Detail view Download link is incorrectly wired to /jmx/${testId} instead of actual storage location used by Create view /jmeter/${testId}

### ISSUE THREAD

**Issue by ryanneill-sterling** [awslabs/distributed-load-testing-on-aws#26]
source/console/src/Components/Details/Details.js:202:

const url = await Storage.get(`test-scenarios/jmx/${testId}.jmx`, { expires: 10 });

Should be:

const url = await Storage.get(`test-scenarios/jmeter/${testId}.jmx`, { expires: 10 });

**Comment by beomseoklee** [comment]
@ryanneill-sterling Thanks for your feedback, and we are already aware of that. That one will be fixed in the next version.

**Comment by beomseoklee** [comment]
@ryanneill-sterling We've released v1.2.0, and this has been fixed.
https://github.com/awslabs/distributed-load-testing-on-aws/blob/339482f2ee9a1501b4db49da33cd656c6f3f6110/source/console/src/Components/Details/Details.js#L223-L234

**Comment by ryanneill-sterling** [comment]
Thank you!
