### ISSUE TITLE
Was there a reason this was set to create a new VPC?

### ISSUE THREAD

**Issue by Vermyndax** [awslabs/distributed-load-testing-on-aws#27]
We'd like to use this, but have a strict policy against creating new VPC's. Was there a best-practice/reason for creating a new VPC for this solution?

**Comment by beomseoklee** [comment]
@Vermyndax Thanks for contacting us. We just create a new VPC not to mess up the existing VPC environment. We can think of supporting the existing VPC instead in the future. By the way, do you have any other obstacles to use the solution?

**Comment by sc-alscient** [comment]
I am not OP, but another handy feature would be an optional NAT GW with Elastic IP. This would allow testing of IP restricted environments. Its easy enough to add to the template, but would be nice if it was included by default as an option.

**Comment by Vermyndax** [comment]
The VPC creation was our only real hurdle. We forked and modified the template to add the VPC as an option. We just wanted to make sure there wasn't a reason otherwise.

**Comment by RWMulayAhmed** [comment]
same here @Vermyndax , we had to keep a version of this and maintain it due to the requirement to create a new VPC. 
@beomseoklee  It's important to give the option to point Farge to an existing VPC.

**Comment by beomseoklee** [comment]
Thanks all for the valuable feedback, and we put this one to the backlog item so that we can implement this one in the next release.

**Comment by aridastidar** [comment]
@beomseoklee Excellent! Just curious about the timing of the next release? Asking since we are in the same boat and would like to use an existing VPC as the target rather than setup a new VOC from scratch and don’t want to maintain a fork to make it work if this is coming sooner. Thanks to the team for putting together this nifty solution that just works!

**Comment by emcfins** [comment]
As of the latest release, v2.0, you can specify an existing VPC that will be used by the testing tasks rather than creating a new one.
