### ISSUE TITLE
JMeter Support

### ISSUE THREAD

**Issue by QAInsights** [awslabs/distributed-load-testing-on-aws#3]
Executing JMeter scripts from the web console by uploading *.jmx and its dependencies would be a great feature to have.

**Comment by tomnight** [comment]
Greate feedback thank you, this was the first version and we are looking for this type of feedback to drive future releases. I will ad this to the road map.

**Comment by QAInsights** [comment]
@tomnight Also, please add Gatling tool as well to your roadmap :)

**Comment by voycey** [comment]
Is there a way to upload these JMX tests to somewhere and be able to execute them on the infrastructure? It is literally as easy as ```bzt test.jmx```

**Comment by QAInsights** [comment]
@voycey at this moment, it is not possible.

**Comment by QAInsights** [comment]
@tomnight any updates on the jmeter integration. Could you please publish the public roadmap? Thanks!

**Comment by tomnight** [comment]
Unfortunately I don't have any details I can share for the road map except to say Jmeter support is at the top of the list. I will reach out when I have more.

**Comment by beomseoklee** [comment]
We've released v1.1.0, and v1.1.0 includes JMeter script support so you can upload your existing JMeter script. Please see the details in [CHANGELOG](https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/CHANGELOG.md).

**Comment by surajshinde18** [comment]
Is this solution supports Jmeter scripts which requires csv inputs? Is there any work around?
