### ISSUE TITLE
Please provide sample of HTTP Headers 

### ISSUE THREAD

**Issue by ivarva** [awslabs/distributed-load-testing-on-aws#36]
**What is your question?**

When trying to pass API Key as header parameter I am getting error "WARNING: headers text is not valid JSON". 

Please provide sample with expected format.

**Comment by beomseoklee** [comment]
@ivarva it should be `JSON` format. 
For example,
```json
{ "key": "value", "otherkey": "othervalue" }
```

Please let us know if it is not working for you again.

**Comment by ivarva** [comment]
@beomseoklee Thank you for your comment, I have tried and it is giving me validation error. Can you please test with the app UI and provide me with the real sample that works for you. Thank you

**Comment by ivarva** [comment]
Format that worked: 
{
  "x-api-key": "GtGsXWgFY45UOdsJtKdZZ1Xptk5GFTcD7gw57J8E"
}
