### ISSUE TITLE
How to find out what cause test failed - Failed to run Fargate tasks.

### ISSUE THREAD

**Issue by ensean** [awslabs/distributed-load-testing-on-aws#41]
**What is your question?**

![image](https://user-images.githubusercontent.com/12255172/111969639-6e00b600-8b35-11eb-93d2-292e124cc4d4.png)

**Comment by beomseoklee** [comment]
@ensean It seems like that happens in the API Lambda function, so you can find the error in the CloudWatch logs of the API Lambda function which would be `<YOUR_STACK_NAME>-ApiServices-<HASH>`.

**Comment by colthurst-say** [comment]
Getting the same error - and seeing in our cloudwatch logs for /aws/lambda/[STACK NAME] 
ERROR	InvalidParameterException: Error retrieving security group information for [sg-XXXXXXXXXXX]: Request limit exceeded. (ErrorCode: RequestLimitExceeded)

**Comment by beomseoklee** [comment]
@colthurst-say I'm sorry to hear you experienced an issue. Your log seems related to the request limit which the solution can't resolve so it would be better to reach out to AWS support or forum for your issue.
