### ISSUE TITLE
Unable to access objects in logsbucket

### ISSUE THREAD

**Issue by ocsalon** [awslabs/distributed-load-testing-on-aws#45]
Version v1.2.0
![image](https://user-images.githubusercontent.com/64600925/113756994-53027a00-96cf-11eb-9cc8-cd51d187860c.png)
I'm unable to access any object that is put in the logsbucket, I believe this is because the ownership of the objects is set to the object writer. I'm concerned after checking the canonical ID of the objects inside the logsbucket I see it differs from the canonical ID of my AWS account, is this supposed to be that way?

**Comment by beomseoklee** [comment]
@ocsalon thanks for your feedback. The canonical ID you are seeing is for CloudFront access log. Please refer to this [link](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#AccessLogsBucketAndFileOwnership) for more information.

For the log access, I believe you can download and see the inside contents. Please refer to this [link](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html) for more information.

**Comment by ocsalon** [comment]
Hi @beomseoklee thanks for replying. 

I now understand where the canonical ID comes from. 

Regarding the log access, I apologize, it seems I didn't provide enough context. I'm trying to access the objects recorded inside the **logsbucket** (created by the cloudformation stack) from the S3 web console, I have full accesss on the AWS account, however, I'm unable to access any object, when I try to download I get: 
![image](https://user-images.githubusercontent.com/64600925/113943683-63dee880-97c0-11eb-857b-4a87df901420.png)

Any other bucket created by the cloudformation stack I'm able to access without issues.

**Comment by beomseoklee** [comment]
@ocsalon did you click the Object URL on the S3 console? If so, you will not download or see the object as because the buckets are not allowed public access. Instead, can you click Actions or Object Actions button and choose Download?
![image](https://user-images.githubusercontent.com/22212362/114056874-f5913900-9846-11eb-9982-52737b841687.png)
