### ISSUE TITLE
API execution example

### ISSUE THREAD

**Issue by veltz-avi** [awslabs/distributed-load-testing-on-aws#47]
Can you please share an example of how to execute the API from the command line? e.g. using curl.

Is there any configuration change that needs to be done on the API-Gateway or Cognito to allow the APIs to work?

Thanks,

**Comment by beomseoklee** [comment]
@veltz-avi you can call the API directly by signing the request. Please refer to the below documents and source code:
- [API Gateway signing request](https://docs.aws.amazon.com/apigateway/api-reference/signing-requests/)
- [Create test scenario API](https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/appendix-d.html#post-scenarios)
- [Reference to create the API body payload](https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/source/console/src/Components/Create/Create.js#L124-L191)
