### ISSUE TITLE
Uploading large zip file for testing fails

### ISSUE THREAD

**Issue by naxxster** [awslabs/distributed-load-testing-on-aws#49]
**Describe the bug**
When I creating a test case using .zip file, the uploading of the zip file fails.

**To Reproduce**

1. Write any jmx test file
2. Archive test file to .zip file (which is over 12MB)
3. Make test case with the .zip file
4. upload fails

**Expected behavior**
The upload should be success and the scenario bucket should have upload zip file with newly created scenario id.

**Please complete the following information about the solution:**
- [x] Version: v1.2.0
- [x] Region: ap-northeast-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
![Screen Shot 2021-04-19 at 11 34 41 PM](https://user-images.githubusercontent.com/354974/115253916-d4deb280-a167-11eb-981f-4e2cd1144a2d.png)

![Screen Shot 2021-04-19 at 11 45 32 PM](https://user-images.githubusercontent.com/354974/115255630-6ac70d00-a169-11eb-84d2-3855dee1a8b9.png)

**Additional context**

**Comment by beomseoklee** [comment]
@naxxster thanks for your feedback. We'll investigate this issue.
