### ISSUE TITLE
Support for integrating with a DB (for seed data) and InfluxDB outside this solution

### ISSUE THREAD

**Issue by madhu-gudivaka** [awslabs/distributed-load-testing-on-aws#54]
Hi,

In cases where the seed data used in JMeter scripts (as in a pool of UID/Pwds, application transaction data used in scripted workflows etc) is stored in a DB (in our case MySQL DB), how do we have the JMeter Master/Slaves communicate with a persistent DB outside this solution via JDBC connection configuration?

Similarly, we use an influxDB backend listener to write test results to which could be visualized in Grafana dashboard realtime or afterwards.

So, if there is a way the aws services running the JMeter tests in this solution can communicate with **persistent** seed data DB and influx DB hosted onPrem -OR- on EC2 instances in AWS, it would enhance the scenarios enormously in which this solution can be used and adapted by many.

Can you please clarify if this can be done now and how?  If not, can you please add this capability to feature roadmap

**Comment by beomseoklee** [comment]
@madhu-gudivaka Thanks for your feedback. Currently, the solution creates a VPC to host AWS Fargate tasks, and if you want to connect to your DB in anywhere, you need to configure the connection between the solution created VPC and on-premises or other AWS VPCs.

We have a backlog item to support the existing VPC, so I think that would make more flexible to use the solution in your scenario.

**Comment by emcfins** [comment]
The latest release, v2.0, now supports using an existing VPC.
