### ISSUE TITLE
SSO Integration

### ISSUE THREAD

**Issue by tpark-itops** [awslabs/distributed-load-testing-on-aws#59]
**What is your question?**

Is it possible for the solution to be SSO integrated? I've been trying to configure Cognito UserPool to work with Azure AD SSO, but so far no luck.  Any guidance or assistance would be much appreciated.

**Comment by emcfins** [comment]
This would be a configuration within the Cognito UserPool. 

We found this blog post that may help you with the integration with Azure AD SSO: [https://medium.com/@zippicoder/setup-aws-cognito-user-pool-with-an-azure-ad-identity-provider-to-perform-single-sign-on-sso-7ff5aa36fc2a](https://medium.com/@zippicoder/setup-aws-cognito-user-pool-with-an-azure-ad-identity-provider-to-perform-single-sign-on-sso-7ff5aa36fc2a)

**Comment by tpark-itops** [comment]
Thanks, I was able to display SSO authentication login page following the integration instruction, but it did not log me into DLTA solution. Would it require some sort of customization to DLTA ReactJS app?

**Comment by emcfins** [comment]
The solution uses Amplify - this is the documentation that describes how to use federated sign in: https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation
