### ISSUE TITLE
Option to manage two or more Jmeter Thread Group Properties

### ISSUE THREAD

**Issue by oscarlopezsastre** [awslabs/distributed-load-testing-on-aws#61]
Is there an option to configure more than one Jmeter thread group in the "Create Load Test" window?
Specifically the parameters "concurrency", "ramp up" and "hold for" for Jmeter scripts with more than one thread group.
Thanks

**Comment by G-Lenz** [comment]
Hi @oscarlopezsastre The UI itself does not provide those options, however, you can define thread groups within a custom Jmeter script that you can upload when creating a test.

**Comment by oscarlopezsastre** [comment]
Hi George,
Thanks for your response.
In this case (with multiple thread groups), would all thread groups get the same defined configuration in the "Create Load Test" window?
This option would not be very flexible on my side, it would be nice to be able to configure each thread group independently.

**Comment by G-Lenz** [comment]
@oscarlopezsastre Distributed load testing uses Taurus, which serves as an abstraction layer on top of JMeter. The parameters defined in the UI go into a Taurus yaml file. When concurrency is defined in both Taurus and Jmeter thread groups, Taurus uses the values in each thread group as a ratio of the concurrency defined in Taurus. You can a more thorough explanation about how Taurus works with JMeter thread groups in the [Taurus documentation](https://gettaurus.org/docs/JMeter/#Run-Existing-JMX-File).
