### ISSUE TITLE
Test id starting with "-" will cause failure of uploading result files.

### ISSUE THREAD

**Issue by horietakehiro** [awslabs/distributed-load-testing-on-aws#62]
Test id, which is automatically and randomly generated in creating test scenarios, sometimes starts with "-" (e.g. "-jafifg"). Such test id causes error in "load-test.sh".
```.Bash
    cat $TEST_ID.jmx | grep filename > results.txt
```
If test id is "-jafifg", command above equals to "cat -jafifg.jmx" and will cause an error like `cat: invalid option -- 'j'`. This results in failure of whole uploading process in load-test.sh.

I expect that test id which starts with "-" never be generated.

**Comment by emcfins** [comment]
Thank you for opening this issue. We will update this in our next release.

**Comment by emcfins** [comment]
We have updated this in our new release.

Thank you for your feedback.
