### ISSUE TITLE
Fix Spelling of Amazon

### ISSUE THREAD

**Issue by drumadrian** [awslabs/distributed-load-testing-on-aws#8]
On the README.md page: 
https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/README.md

Amazon is misspelled as "Amaazon" 

on line 37

Link:
https://github.com/awslabs/distributed-load-testing-on-aws/blame/master/README.md#L37

**Comment by beomseoklee** [comment]
@drumadrian We've released v1.2.0, and we've fixed typos. Thanks for your feedback.

**Comment by drumadrian** [comment]
thank you @beomseoklee   

This project inspired me to build a custom Fargate-based load test using the AWS CDK.  I'm happy to share what I learn and build if you want me to.
